# 1. Cài đặt Bun (Thay thế Node.js và npm)
[phases.setup]
nixPkgs = ["bun"]

# 2. Cài đặt thư viện bằng Bun (Bun xử lý native binding cực tốt)
[phases.install]
cmds = [
    "rm -rf node_modules package-lock.json pnpm-lock.yaml", # Xóa sạch cũ
    "bun install --no-save"                                 # Cài bằng Bun
]

# 3. Build Project
[phases.build]
cmds = ["bun run build"]

# 4. Khởi chạy
[start]
cmd = "node .output/server/index.mjs"
