# 1. Cài đặt Node.js version 22 (Mới nhất để tương thích Nuxt 3.12+)
[phases.setup]
nixPkgs = ["nodejs_22"]

# 2. Cài đặt thư viện (Ghi đè pha install mặc định để tránh lỗi npm ci)
[phases.install]
cmds = ["npm install"]

# 3. Build Project
[phases.build]
cmds = ["npm run build"]

# 4. Khởi chạy
[start]
cmd = "node .output/server/index.mjs"
